from .msg_loader import MsgContext
from .msgs import MsgSpec

def compute_md5_text(msg_context: MsgContext, spec: MsgSpec) -> str: ...
def compute_md5(msg_context: MsgContext, spec: MsgSpec) -> str: ...

# alias
compute_md5_v2 = compute_md5

def compute_full_text(msg_context: MsgContext, spec: MsgSpec) -> str: ...
def compute_full_type_name(package_name: str, file_name: str) -> str: ...
