from typing import Optional, Pattern

PRN_SEPARATOR: str

def normalize_package_context(package_context: str) -> str: ...
def resource_name(res_pkg_name: str, name: str, my_pkg: Optional[str] = ...) -> str: ...
def resource_name_base(name: str) -> str: ...
def resource_name_package(name: str) -> str: ...
def package_resource_name(name: str) -> str: ...

RESOURCE_NAME_LEGAL_CHARS_P: Pattern[str]

def is_legal_resource_name(name: str) -> bool: ...

BASE_RESOURCE_NAME_LEGAL_CHARS_P: Pattern[str]

def is_legal_resource_base_name(name: str) -> bool: ...
