from typing import Any

class SrvSpec:
    request: str = ...
    response: str = ...
    text: str = ...
    full_name: str = ...
    short_name: str = ...
    package: str = ...
    def __init__(
        self,
        request: str,
        response: str,
        text: str,
        full_name: str = ...,
        short_name: str = ...,
        package: str = ...,
    ) -> None: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
