# WARNING: Automatically generated by stubgen
# Needs to be fixed manually

from rospy.impl.tcpros_base import DEFAULT_BUFF_SIZE as DEFAULT_BUFF_SIZE
from rospy.impl.tcpros_base import init_tcpros_server as init_tcpros_server
from rospy.impl.tcpros_pubsub import TCPROSHandler as TCPROSHandler

def init_tcpros(port: int = ...) -> None: ...
def get_tcpros_handler(): ...
