# WARNING: Automatically generated by stubgen
# Needs to be fixed manually

from typing import Any

class ParameterInvalid(Exception):
    def __init__(self, message: Any) -> None: ...

def non_empty(param_name: Any): ...
