from .rostime import Time

class ROSException(Exception): ...
class ROSSerializationException(ROSException): ...
class ROSInitException(ROSException): ...
class ROSInterruptException(ROSException, KeyboardInterrupt): ...

class ROSTimeMovedBackwardsException(ROSInterruptException):
    time: Time = ...
    def __init__(self, time: Time) -> None: ...

class ROSInternalException(Exception): ...
class TransportException(ROSInternalException): ...
class TransportTerminated(TransportException): ...
class TransportInitError(TransportException): ...
