from typing import Any, Callable, Iterator

from .core import xmlrpcclient

class MasterProxy:
    target: xmlrpcclient.ServerProxy = ...
    def __init__(self, uri: str) -> None: ...
    def __getattr__(self, key: str) -> Callable[..., Any]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, val: Any) -> None: ...
    def search_param(self, key: str) -> str: ...
    def get_param_cached(self, key: str) -> Any: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
