name: Build artifacts
on:
  push:
  pull_request:
    branches:
      - master

env:
  DEBIAN_FRONTEND: noninteractive
  MASTER_BRANCH: refs/heads/master
  VERSION_PIPENV: 2020.11.15
jobs:
  build-stubs:
    name: Build ros_stubs
    runs-on: ubuntu-latest
    container:
      image: ros:melodic-ros-core
    steps:
    - name: Set up apt
      run: |
          apt-get update -y
          apt-get install -y --no-install-recommends software-properties-common
    - name: Set up git and ssh
      run: |
          # In order to create a local git repository
          # in actions/checkout@v2, git>=2.18 is required
          add-apt-repository ppa:git-core/ppa
          apt-get update -y
          apt-get install -y --no-install-recommends git git-lfs openssh-client
    - uses: actions/checkout@v2
    - name: Set up Python
      run: |
          apt-get install -y --no-install-recommends \
            python3-pip \
            python3.8 \
            python3.8-dev
          pip3 install pipenv==${{ env.VERSION_PIPENV }}
    - name: Prepare build env
      run: |
          cd assets/
          pipenv sync
          git lfs install
    - name: Build and push artifacts
      if: github.ref == env.MASTER_BRANCH
      env:
        GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh-agent -a ${SSH_AUTH_SOCK} > /dev/null
          echo "${{ secrets.ROSPYPI_SIMPLE_DEPLOY_KEY }}" > ~/deploy_key
          chmod 600 ~/deploy_key
          ssh-add ~/deploy_key

          cd assets/
          pipenv run python publish_artifacts.py \
            --url git@github.com:rospypi/simple.git \
            --branch stubs_pre --ref-branch stubs --push
    - name: Build artifacts
      if: github.ref != env.MASTER_BRANCH
      run: |
          cd assets/
          pipenv run python publish_artifacts.py
